name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:

  release-test:
    runs-on: ubuntu-latest
    steps:

      - name: Remove large directories
        run: |
          df -h
          cd /opt/hostedtoolcache
          find . -mindepth 1 -maxdepth 1 -type d -not -name 'go' -exec rm -rf {} +
          df -h
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: '1.22.6'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --draft=true -p 1
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASE_TOKEN }}
